### ISSUE TITLE
Implementing feedback quiz / knowledge quiz

### ISSUE THREAD

**Issue by Adrian-Moldovan** [fnitu/edu-hospice#107]
On creating a quiz, the admin should specify the type of the quiz

### Feedback quiz vs Knowledge quiz

- [x]  Choosing a feedback quiz, should hide the quiz settings
- [x] Choosing a knowledge quiz should display the quiz settings and make them mandatory
- [x] Changing the type of the quiz should reset the saved questions
- [x] Choosing a feedback quiz will cancel the existence of a correct answer

### Knowledge quiz with restricted access to next section
- [x] Choosing a knowledge quiz should display a toggle for restricting the access to the next course section

### Quiz form modification
In the quiz setting request, two new form field will be submitted: 
- quiz_type (enum: FEEDBACK_QUIZ, KNOWLEDGE_QUIZ) 
- restrict_next_content  (BOOLEAN)

The issue should be implemented after #72 
- [x] Quiz type should be displayed in quiz list

**Comment by razvantudorache** [comment]
Questions for BE:
Quiz settings (attempts, min score, etc) that are hidden for feedback quiz should be sent to server?

**Comment by Adrian-Moldovan** [comment]
We created a ticket for the issue: 
https://github.com/danutchindris/edu-hospice-api/issues/252

We will have an answer in the next team meeting

**Comment by Adrian-Moldovan** [comment]
Implemented successfully :)
