### ISSUE TITLE
Admin quiz create question

### ISSUE THREAD

**Issue by fnitu** [fnitu/edu-hospice#20]
In the "New quiz page" we should have a section that allow the creation of multiple questions:
Fields:

1. question - input / name in model
2. question type: single choice (radio/select), multiple choice(checkbox group) - 3 types, enum: radio/select/checkbox
3. Define possible options (list of option names + Boolean attribute to mark the correct ones):

```json
[
 {
  name: "question text"
  type: "radio/select/checkboxes"
  options: 
   [ { option: "first option", valid: true},  { option: "second option", valid: false } ]
 }
]
```

The order of the questions and question options will be given by the order of the array.

A validation (BE/FE) should be done when selecting the question type to have at least one option.

Drag and drop - to be handled in a separate ticket

**Comment by fnitu** [comment]
To be checked with the server endpoint.

**Comment by fnitu** [comment]
We need to save first the quiz details. The new question card will not be displayed before.

After saving the quiz details, a new request has to be done to the server using the received quiz id from the previous call. This request will create a question. e.g. (quiz/<quiz_id>/create-question)

The response will contain the id of the question that will be set in the new quiz question card.

The new question card will contain a save button, that will be used for updating. When saving the question, the question id + the question details.

When clicking the "Add question", a save action will be performed, followed on success by a new request to the quiz/<quiz_id>/create-question URL.

**Comment by fnitu** [comment]
After further analysis, in order to make it more similar with the course content creation, the following will apply:

We need to save first the quiz details. The new question card will not be displayed before.

After saving the quiz details, the default question + default options will be created on the client. The card will contain a save button. When this is clicked, a POST request will be submitted to /api/admin/quizzes/{quizId}/questions.

**Comment by razvantudorache** [comment]
- add question feature has been implemented as requested 
- save button has been added (not yet integrated with server API)
![2021-05-15_20h52_24](https://user-images.githubusercontent.com/18479007/118373440-7ae2d880-b5bf-11eb-9f59-08b156afbfbd.png)
![2021-05-15_20h52_30](https://user-images.githubusercontent.com/18479007/118373442-7b7b6f00-b5bf-11eb-8124-d848cd22c7fc.png)

**Comment by fnitu** [comment]
Hi @razvantudorache ,

Please update the "Save" button on the questionnaire details to use the green color, same as for questions.

Please move the "Add question" and "Delete" buttons to the left side of the question card. On the right hand side, only the "Save" button should remain.

**Comment by razvantudorache** [comment]
Modifications from the last comment have been applied.
Waiting for server integration:
- save question
- get quiz settings
- get quiz questions

**Comment by razvantudorache** [comment]
Hi,

All new quiz APIs have been integrated.

A new end-point is requested for deleting a question.

**Comment by fnitu** [comment]
Hi,

Please change the routes to admin/quiz-list/quiz and admin/quiz-list/quiz/:id. The routes should be parent/child with quiz-list.

**Comment by razvantudorache** [comment]
Hi,

The route has been modified as requested (quiz-list/quiz and quiz-list/quiz/:id) but without the relation parent - child with quiz-list. In order to have that relation a new page must be created that will contain another router-outlet. 

From my opinion this relation is not needed because these two pages (quiz-list and quiz) don't have common elements to require a router-outlet (in order to refresh just a part of the page).
