### ISSUE TITLE
Show course content as cards

### ISSUE THREAD

**Issue by fnitu** [fnitu/edu-hospice#29]
For users, the course content should be shown as a sidenav (https://material.angular.io/components/sidenav/overview), the course items inside should be displayed as a tree: https://material.angular.io/components/tree/overview

The course items should contain: icon, name, status and they should ALL be expanded by default.

The sidenav should be collapsible.

Route to be modified: user/course/course/1

**Comment by fnitu** [comment]
Working on integration of Material tree

**Comment by fnitu** [comment]
Basic integration was done, working on loading the content when clicking the tree.

**Comment by fnitu** [comment]
URL to be used for server data: https://edu-hospice-api.herokuapp.com/swagger-ui.html#/user-course-controller/retrieveUserCourseDetailsUsingGET

**Comment by fnitu** [comment]
@TudorPetruToma Please commit your changes.

@razvantudorache Please take over the task after the changes are committed.

**Comment by razvantudorache** [comment]
![WhatsApp Image 2021-01-26 at 18 56 38](https://user-images.githubusercontent.com/18479007/109432061-18435d00-7a12-11eb-8b34-cfbe6053a5ee.jpeg)
