### ISSUE TITLE
Show list of users that need to be validated by admin after registration

### ISSUE THREAD

**Issue by fnitu** [fnitu/edu-hospice#32]
After an user registers to a course, it will be visible in a list that can be accessed from the admin dashboard. The admin can accept the registration. This does **not** grant access to the course! 

#33 needs to be implemented for the user to have access to the course.

Both lists #32 and #33 will be shown as tabs in the same page.

**Comment by razvantudorache** [comment]
This ticket is on-hold, waiting for BE integration

**Comment by fnitu** [comment]
Related BE issue: edu-hospice-api#41

**Comment by razvantudorache** [comment]
![2021-02-02_19h55_36](https://user-images.githubusercontent.com/18479007/106642148-aa318480-6590-11eb-93c5-5473f866cc4e.png)

**Comment by fnitu** [comment]
Documentation URL for integration: https://edu-hospice-api.herokuapp.com/swagger-ui.html#/user-course-controller/getAllUsersRegistrationPendingUsingGET

**Comment by razvantudorache** [comment]
API has been integrated
