### ISSUE TITLE
Show list of users that need to be validated by admin after course payment

### ISSUE THREAD

**Issue by fnitu** [fnitu/edu-hospice#33]
After an user has been accepted by an admin as registered for a course, it will be visible in a list that can be accessed from the admin dashboard. The admin can validate that the user has made the payment for the course. Only after this step, the user will be able to access the course.

**Comment by razvantudorache** [comment]
This ticket is on-hold, waiting for BE integration

**Comment by fnitu** [comment]
Related BE issue: edu-hospice-api#42

**Comment by fnitu** [comment]
URL for the third tab, all users: /api/admin/users/courses

**Comment by fnitu** [comment]
URL for integration: https://edu-hospice-api.herokuapp.com/swagger-ui.html#/user-course-controller/getAllUsersPaymentPendingUsingGET

**Comment by razvantudorache** [comment]
APIs have been integrated
