### ISSUE TITLE
Integration with server of forgot/reset password feature 

### ISSUE THREAD

**Issue by fnitu** [fnitu/edu-hospice#34]
#14 and #15 must be integrated with server.

On #14 a confirmation message must be displayed when an e-mail is sent successfully.

TODO: Use translation keys.

**Comment by razvantudorache** [comment]
Hi @RaduMS ,

Please review your implementation that uses **matSnackBar**. I see that you configured matSnackBar with an action, that is not really an action. It acts like a notification type indicator. 

                if (response.success) {
                    action = GLOBALS.constants.NOTIFICATIONS.INFO;
                } else {
                    action = GLOBALS.constants.NOTIFICATIONS.ERROR;
                }

                this.matSnackBar.open(response.message, action, {
                    duration: GLOBALS.constants.NOTIFICATIONS.DURATION_IN_SECONDS * 1000,
                    verticalPosition: 'top'
                });

               this.matSnackBar.open(result.message, GLOBALS.constants.NOTIFICATIONS.INFO, {
                    duration: GLOBALS.constants.NOTIFICATIONS.DURATION_IN_SECONDS * 1000,
                    verticalPosition: 'top'
                });

I propose to remove that configuration because in all case it's looks the same (having the red color).

**Comment by fnitu** [comment]
Waiting for the e-mail topic to be handled.

**Comment by fnitu** [comment]
Remove unnecessary parameters that are sent to server, only e-mail should be needed.

**Comment by fnitu** [comment]
To be checked with the new server URL.

**Comment by fnitu** [comment]
Issue implemented and tested.
