### ISSUE TITLE
Style admin dashboard

### ISSUE THREAD

**Issue by fnitu** [fnitu/edu-hospice#43]
Style admin dashboard, based on design input

**Comment by DanNerghes** [comment]
![admin_dashboard](https://user-images.githubusercontent.com/66696511/106315549-0e440800-6274-11eb-9cfa-6c00e9614556.png)

**Comment by fnitu** [comment]
Waiting for design.

**Comment by fnitu** [comment]
Update translations to use title + description in keys.
