### ISSUE TITLE
Navigate to specific user tab from admin dashboard

### ISSUE THREAD

**Issue by fnitu** [fnitu/edu-hospice#46]
Admin must be able to directly navigate using the shortcuts from dashboard to a specific user tab:

1. pending registrations
2. pending payment
3. all users

Most likely, an URL param must be sent and the tab component to take it into account.

**Comment by fnitu** [comment]
Active tab is not highlighted.

**Comment by fnitu** [comment]
The all users tab should make a request to: /api/admin/users/courses/stats instead of: /api/admin/users/courses

**Comment by razvantudorache** [comment]
- the url for the 3rd tab has been updated
- the list for the 3rd tab has been updated with the correct columns (no. of pending, finalized and ongoing 
- the router url is updated on tab change
- tab active has the same styling as on focus
