### ISSUE TITLE
Add production API URL to build process

### ISSUE THREAD

**Issue by fnitu** [fnitu/edu-hospice#47]
Check how to build the application to use a different URL for the API requests (a production one instead of the current Heroku development).

References: https://www.jvandemo.com/how-to-use-environment-variables-to-configure-your-angular-application-without-a-rebuild/

**Comment by razvantudorache** [comment]
For heroku production:
- [environment file](https://github.com/fnitu/edu-hospice/blob/master/src/environments/environment-heroku.prod.ts)
- [angular configuration](https://github.com/fnitu/edu-hospice/blob/c7588c033a0eb563514632bc847381447b679804/angular.json#L87)

For production: 
- [environment file](https://github.com/fnitu/edu-hospice/blob/master/src/environments/environment.prod.ts)
- [angular configuration](https://github.com/fnitu/edu-hospice/blob/c7588c033a0eb563514632bc847381447b679804/angular.json#L59)

BASE_URL has been moved from **globals** to **environment** and must be used from there.
