### ISSUE TITLE
Integration of approve/reject course registration/payment pending

### ISSUE THREAD

**Issue by fnitu** [fnitu/edu-hospice#52]
Implementation of the following URLs:
https://edu-hospice-api.herokuapp.com/swagger-ui.html#/user-course-controller/approveUserCourseUsingPUT
https://edu-hospice-api.herokuapp.com/swagger-ui.html#/user-course-controller/rejectCourseRegistrationUsingPUT

The same URLs are used on both pages to do the actions.

**Comment by fnitu** [comment]
@RaduMS please test with multiple data.

**Comment by fnitu** [comment]
Issue moved to backlog to be finalized when the approval topic is resumed.

**Comment by RaduMS** [comment]
Add grid refresh for grid approve and reject event.

**Comment by fnitu** [comment]
Implemented.
