### ISSUE TITLE
Admin quiz templates list

### ISSUE THREAD

**Issue by fnitu** [fnitu/edu-hospice#57]
Add a new quiz section on the admin dashboard, that will take you to a new page, that will contain the existing quiz list.

The fields displayed will be:

1. Quiz name
2. Quiz status (active/inactive) - it will be available for selection in the course creation page, initially inactive
3. Number of assigned questions
4. Last update (date)
5. Creation date 

A new icon should be provided by design.

You will also have a "New quiz" button in this page. The pre-requisite implementation from #58 should also be re-used here.

Related: https://github.com/danutchindris/edu-hospice-api/issues/127

**Comment by fnitu** [comment]
To be integrated with BE endpoint: https://edu-hospice-api.herokuapp.com/swagger-ui.html#/quiz-controller/getQuizzesUsingGET

API URL: _/api/admin/quizzes_

**Comment by fnitu** [comment]
Add hour to last update column, please.

**Comment by fnitu** [comment]
Please check if id is received from server.

**Comment by DanNerghes** [comment]
![id-check](https://user-images.githubusercontent.com/66696511/115952617-a8bc8c00-a4ef-11eb-943a-1de0e5e64c29.PNG)

There is no id in quiz list response from server, yet.
