### ISSUE TITLE
Move Bearer header to http interceptor

### ISSUE THREAD

**Issue by fnitu** [fnitu/edu-hospice#6]
Move Bearer header to http interceptor in order for it to be set in one place
Remove token from URL, to be stored in cookie, localStorage, etc.

https://medium.com/@ryanchenkie_40935/angular-authentication-using-the-http-client-and-http-interceptors-2f9d1540eb8

**Comment by razvantudorache** [comment]
- interceptor implemented
- auth service implemented
- token and user details stored on session storage
- Globals class created for common constants
- user details request has been removed - user details used from session storage

**Comment by razvantudorache** [comment]
- bug generated on refresh dashboard page has been fixed
