### ISSUE TITLE
Add dialog for homepage card

### ISSUE THREAD

**Issue by ancutadaniel** [fnitu/edu-hospice#64]
When clicking on a card, a call must be done to: /api/courses/{id} The response fields will be shown in the card.

The exact fields and design is to be determined, the API will be updated following the decision of the exact fields.

When clicking the card, a query param should be added to the URL: https://www.digitalocean.com/community/tutorials/angular-query-parameters

This query param should not trigger the refresh of the route.

If you press F5 and go directly to a page with a query param set, the dialog should be automatically shown.

Please consider implementing the color scheme using the specification defined in issue: https://github.com/fnitu/edu-hospice/issues/98

**Comment by fnitu** [comment]
Please iterate through all the elements from userSectionDetails, in order to display all the sections for a course.

**Comment by fnitu** [comment]
Please update the layout with the specifications from design.

**Comment by fnitu** [comment]
Please make sure no other dialog styling is affected (such as the confirmation dialog from various places).

**Comment by fnitu** [comment]
Please a min width for the dialog.

**Comment by Adrian-Moldovan** [comment]
Please consider implementing the color scheme using the specification defined in issue: https://github.com/fnitu/edu-hospice/issues/98

**Comment by Adrian-Moldovan** [comment]
Issue implemented.
