### ISSUE TITLE
Quiz update features

### ISSUE THREAD

**Issue by fnitu** [fnitu/edu-hospice#72]
Must have
- [x] Add textbox/textarea control - character limit, to be decided if it will be a separate control, or settings for the radio control.
- [x] Add a slider option for the quiz controls: 
- https://material.angular.io/components/slider/examples
- https://angular-slider.github.io/ngx-slider/
- [x] Mark the first option as valid when a question is added (checkbox, single selection, dropdown selection)
- [x] Update the interface: a single *add question* button should be displayed, the newly added question will be appended to the list. The other *add buttons* should be removed.
- [x] The question list should implement a drag and drop interface (https://v9.material.angular.io/cdk/drag-drop/overview)
- [x] Create formly field for the new field type - slider/ textare big/ textare small, including the new display option for radio field
- [x] Save questions after each drag and drop action. A list containing the questions ids must be sent to the server on URL: https://github.com/danutchindris/edu-hospice-api/issues/235
- [x] Question settings
Some of the question types will have a settings property, eg:
 - The LINEAR_SCALE will have: min_value, max_value; these values will be specified by the user in the UI
 - The TEXTAREA_SMALL will have: max length; this value will be hardcoded for now, having a value of 500
 - The TEXTAREA_BIG will have: max length; this value will be hardcoded for now, having a value of 2000

Nice to have: 
 - [x] Adding a question should scroll to bottom
 - [x] Dragging a question should scroll the list
 - [x] Add possibility for radio controls to be displayed horizontally/vertically. The radio buttons control  will implement a *direction* property of (vertical | horizontal)

**Comment by razvantudorache** [comment]
Hi,

Two new field types have been added: 
- TEXTAREA_SMALL: limit 500 chars
- TEXTAREA_BIG: limit 2000 chars

![textarea_short](https://user-images.githubusercontent.com/18479007/122985559-031a8180-d3a7-11eb-9a26-91963dd12844.png)
![textarea_big](https://user-images.githubusercontent.com/18479007/122985564-03b31800-d3a7-11eb-8056-8712016fab62.png)

**Comment by razvantudorache** [comment]
New types **TEXTAREA_BIG** and **TEXTAREA_SHORT** must be taken into consideration on server

**Comment by Adrian-Moldovan** [comment]
The expected payload for the **settings** property should be an array of objects

 "settings": [
    {
      "name": "string",
      "value": "string"
    }
]

Please check out the swagger documentation: https://edu-hospice-api.herokuapp.com/swagger-ui.html#/quiz-controller/updateQuestionUsingPUT

**Comment by razvantudorache** [comment]
All points from description have been implemented.
