### ISSUE TITLE
Tracking user progress in a course

### ISSUE THREAD

**Issue by fnitu** [fnitu/edu-hospice#74]
When a user accesses a course page to which he has access (for the first time), he should receive all the course sections + content without having access to:
- content URL
- resourceSummary

The current content is the content that is enabled and does not have a completion date. 

See: https://github.com/danutchindris/edu-hospice-api/issues/207

This content id will be sent to another URL in order to receive:
- content URL
- resourceSummary
See https://github.com/danutchindris/edu-hospice-api/issues/208

A "Finalize content" floating  button should be added (https://material.io/components/buttons-floating-action-button#anatomy). The button should initially have an animation to draw the users attention. To be decided if the button should contain either an icon or a text, or both.

The "Forward" navigation arrow is disabled until the user clicks for the first time the "Finalize content" button.

The "Finalize" action will save also a timestamp, in order to provide future functionalities:
- time of completion
- restriction regarding minimum time needed for finalization of one content unit

Clicking the "Finalize" button will submit  request to the server, containing the current content id. The server response will provide:
- the id of the next content 
- the progress percentage
- the saved timestamp of completion of the submitted content id
See: https://github.com/danutchindris/edu-hospice-api/issues/209

After receiving the server response, the following will happen: 
- the next section on the course content tree will be enabled. 
- the progress bar will have to be incremented 
- the user will be navigated to the next content unit.

**Comment by razvantudorache** [comment]
All the features mentioned in description have been implemented as requested. 

The modifications can be checked on the platform, but for the moment there is no other course enabled and not completed.
