### ISSUE TITLE
Edit user profile

### ISSUE THREAD

**Issue by fnitu** [fnitu/edu-hospice#76]
A registered user should be able to update the personal data he has filled in at registration time: https://edu-hospice.herokuapp.com/#/preview/register

The profile is accessible from the profile icon in the navigation top bar.

To be decided if we want to allow the user to upload a profile picture or to select from predefined profile pictures.

A dashboard icon should also be added, similar to the admin dashboard icon. 

On the admin side, a profile icon should be added but the redirect link will be implemented in the future #77.

**Comment by DanNerghes** [comment]
We need an endpoint that returns all user data from registration time, so when edit section is accessed, the form will be pre completed.

**Comment by Adrian-Moldovan** [comment]
Please use the provided endpoints:
- for getting the user data:  GET /api/users/current-user/full-details
- for updating the user profile: PUT /api/users/update

**Comment by DanNerghes** [comment]
The email field should be disabled to prevent modifications

**Comment by DanNerghes** [comment]
A validator should be provided for phone number in registration form 

Also check the validation for the other fields

**Comment by DanNerghes** [comment]
gdpr & agreement should be also disabled

**Comment by Adrian-Moldovan** [comment]
Issue closed
