### ISSUE TITLE
User should be able to see the course registration status for the "Pending" tab

### ISSUE THREAD

**Issue by fnitu** [fnitu/edu-hospice#78]
There are only two situations: 
- pending for approval
- pending for payment

Additionally, when the user registers for a course from the "Recommended" tab, he should be redirected to the "Pending" tab and the newly registered course should appear here, with the pending for approval status.

Right now, after a registration action, the user has to refresh the page in order to see new data in the dashboard.

**Comment by Adrian-Moldovan** [comment]
@irinmo @gabstoi we could use a bit of UI/UX magic on this issue

**Comment by irinmo** [comment]
![Screenshot 2021-11-16 at 18 17 06](https://user-images.githubusercontent.com/42898241/142023595-e85896c7-e0f2-4cc9-b2b4-aaef36ba9925.png
![Screenshot 2021-11-16 at 18 18 32](https://user-images.githubusercontent.com/42898241/142023620-22391791-31f4-4c09-ba60-e1e60f6ed934.png)
)

**Comment by irinmo** [comment]
![Screenshot 2021-11-16 at 18 18 32](https://user-images.githubusercontent.com/42898241/142023874-048bdae8-be56-4df6-ba1b-5f5a58747d3c.png)
![Screenshot 2021-11-16 at 18 18 32](https://user-images.githubusercontent.com/42898241/142023907-1b531a65-5737-4595-ad0c-f3f282cc6fda.png)

**Comment by irinmo** [comment]
![Screenshot 2021-11-16 at 18 18 32](https://user-images.githubusercontent.com/42898241/142023969-bf7770eb-aac3-4677-8862-eec6a54a9d28.png)
![Screenshot 2021-11-16 at 18 17 06](https://user-images.githubusercontent.com/42898241/142023981-13b45279-25b8-4ea3-bb69-8d7743c4704e.png)

**Comment by Adrian-Moldovan** [comment]
The pending courses should have one of two statuses:
Registration pending -  "In asteptarea validarii"
Payment pending - "In asteptarea platii"

@gabstoi please design the messages accordingly.

Please change color for payment pending status (not red). The red color should be used in the future for the rejected registered courses.

**Comment by irinmo** [comment]
![Screenshot 2021-11-22 at 18 07 06](https://user-images.githubusercontent.com/42898241/142895408-6fa44d35-4ebc-42d9-871f-86d85d838cff.png)
![Screenshot 2021-11-22 at 18 06 37](https://user-images.githubusercontent.com/42898241/142895421-ac73093e-537d-4570-a94a-a75a309a6a5a.png)

**Comment by irinmo** [comment]
https://www.figma.com/file/8NBzsIN3cwG0QpByxhlwS5/User---Continut-curs?node-id=930%3A261
https://www.figma.com/file/8NBzsIN3cwG0QpByxhlwS5/User---Continut-curs?node-id=930%3A279

**Comment by irinmo** [comment]
![Screenshot 2021-11-22 at 18 07 06](https://user-images.githubusercontent.com/42898241/142895574-680336a2-3840-4efb-b9d8-841494970483.png)
![Screenshot 2021-11-22 at 18 06 37](https://user-images.githubusercontent.com/42898241/142895586-aabfd787-67aa-4d50-8637-1628aefada0c.png)

**Comment by Adrian-Moldovan** [comment]
Please update the design accordingly to the UI specs defined here:
https://github.com/fnitu/edu-hospice/issues/98

**Comment by Adrian-Moldovan** [comment]
Issue implemented
