### ISSUE TITLE
Restyle course registration button

### ISSUE THREAD

**Issue by fnitu** [fnitu/edu-hospice#84]
Please provide an impactful design for the registration action.

**Comment by fnitu** [comment]
Pending UX design.

**Comment by Adrian-Moldovan** [comment]
@irinmo please provide a link / image with the design

**Comment by irinmo** [comment]
![Uploading Screenshot 2021-11-11 at 19.40.51.png…]()

**Comment by irinmo** [comment]
![Screenshot 2021-11-11 at 19 40 51](https://user-images.githubusercontent.com/42898241/141344501-163baa75-7e49-430a-8f0e-4db74d409c9e.png)

**Comment by DanNerghes** [comment]
Role, period and price need to be provided in the course endpoint

**Comment by Adrian-Moldovan** [comment]
1. After registration confirmation, the courses in the recommended tab should be updated. 
2. On each click on a tab(pending, recommended, ongoing), the courses list should be requested from the API (currently they are cached after  the first request).
3. Card footer info pending for backend providing the endDate, courseRole, price course properties. Related backend ticket: https://github.com/danutchindris/edu-hospice-api/issues/223

**Comment by Adrian-Moldovan** [comment]
Please implement a confirmation after clicking the registration button.

**Comment by Adrian-Moldovan** [comment]
Issue closed.
