### ISSUE TITLE
Restyle section/content/resources buttons from course editing tab

### ISSUE THREAD

**Issue by fnitu** [fnitu/edu-hospice#85]
Initially, a color unification of the different types of actions should be sufficient.

They could be grouped by:
- content
- section
- resources

See initially proposed design: https://www.figma.com/proto/71GwXVMHtoBkXwFwMSaSVj/Admin---Adaugare-curs?node-id=10%3A50&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=10%3A50

![2021-10-28_20h14_39](https://user-images.githubusercontent.com/8045181/139303646-58dfe0ad-ef08-45f8-a1ca-214198ff5c8f.png)

**Comment by irinmo** [comment]
![Screenshot 2021-11-11 at 19 43 04](https://user-images.githubusercontent.com/42898241/141344410-c43e2e6d-612f-4ac6-8b26-69973babb96e.png)

**Comment by irinmo** [comment]
https://www.figma.com/file/71GwXVMHtoBkXwFwMSaSVj/Admin---Adaugare-curs

**Comment by Adrian-Moldovan** [comment]
Issue implemented successfully. GG!
