### ISSUE TITLE
Create a toolbar for the course administration interface as an admin

### ISSUE THREAD

**Issue by Adrian-Moldovan** [fnitu/edu-hospice#87]
Please provide a toolbar containing two buttons:
- list all courses
- add a new course

**Comment by razvantudorache** [comment]
![2021-11-11_20h48_57](https://user-images.githubusercontent.com/18479007/141352576-32a6019f-ef43-4dbc-ba74-685a64bbf0d5.png)
Toolbar containing the requested buttons has been added. Also, I added overflow: auto on the main-container element in order to have the top toolbar always fixed.
