### ISSUE TITLE
A course should not be published unless it has at least one content

### ISSUE THREAD

**Issue by Adrian-Moldovan** [fnitu/edu-hospice#90]
On URL :
https://edu-hospice-api.herokuapp.com/api/admin/courses/10

On adding a new course, the "course state" dropdown should be set as disabled with the "unpublished" option selected. The payload "courseState" property should not be sent to the API.

On updating the course, if the course has no content sections, the API will provide an error stating the invalid "courseState" property that should be displayed to the user.

Backend related issue:
https://github.com/danutchindris/edu-hospice-api/issues/220

**Comment by Adrian-Moldovan** [comment]
Implement the **status** dropdown options as follows:
- if the course id is **NOT** found in URL. the dropdown will have only one option: unpublished
- if the course id **IS** found in the URL, the dropdown will have three options: unpublished, published, cancelled

**Comment by razvantudorache** [comment]
Options for the status dropdown has been configured as requested.
