### ISSUE TITLE
Develop the quiz preview interface

### ISSUE THREAD

**Issue by Adrian-Moldovan** [fnitu/edu-hospice#92]
The preview interface should be accessible from 
1. the quiz list clicking a button 
2. from the quiz edit form through the future implemented toolbar(containing list, new, preview)

The quiz will be loaded in a popup after requesting the API the content of the quiz. The response should provide all the questions and possible answers.( API endpoint: /api/admin/quizzes/{quizId}/questions/details)

The quiz controls will be displayed according to the API data.

**Comment by razvantudorache** [comment]
![2021-12-02_19h46_55](https://user-images.githubusercontent.com/18479007/144475841-080944e3-cb21-4aef-9391-fcb2f0ba24d1.png)
![2021-12-02_19h47_24](https://user-images.githubusercontent.com/18479007/144475847-93993d62-7273-482f-8fdc-431cd5514134.png)
![2021-12-02_19h47_46](https://user-images.githubusercontent.com/18479007/144475849-f203f00c-2748-46cd-bafc-0dc172b57a34.png)
![2021-12-02_19h48_05](https://user-images.githubusercontent.com/18479007/144475852-53a4736a-bece-41dc-9ac3-125f8310cdb0.png)

- the preview button is available in the quiz list and in the quiz edit page
- the preview button is not available for unsaved quiz
- preview is displayed in a popup
