### ISSUE TITLE
On creating the quiz, specify the valid answers

### ISSUE THREAD

**Issue by Adrian-Moldovan** [fnitu/edu-hospice#93]
For  the quiz questions having one of the types:
- dropdown
- radio button
- checkboxes

The admin should be able to mark and answer as valid (singular answer for dropdown and radio, multiple for checkbox)

The API url for sending the question and the answers is : https://edu-hospice-api.herokuapp.com/api/admin/quizzes/questions/2/update

VALIDATIONS: 
At least one answer should be marked as valid
The question text should also be mandatory

**Comment by razvantudorache** [comment]
![2021-12-02_19h53_28](https://user-images.githubusercontent.com/18479007/144476696-8b208e02-f6b9-43b8-b100-882d6b8d56a5.png)
![2021-12-02_19h57_33](https://user-images.githubusercontent.com/18479007/144477318-c47491dc-5213-45af-9763-eccec9cebee8.png)
![2021-12-02_19h58_24](https://user-images.githubusercontent.com/18479007/144477519-cabfda6b-7859-4c7c-bcc5-7f1cf81cad6c.png)
![2021-12-02_19h58_30](https://user-images.githubusercontent.com/18479007/144477524-fd3e22c9-50c7-44db-b321-e089fb931422.png)


- a toggle button has been added for each option to mark the correct option
- for RADIO and SELECT, user can select only one correct option
- multiple correct options can be selected for CHECKBOXES
- validation has been added for empty question name and at least one option to be marked as valid
