### ISSUE TITLE
Specify a template for the popups (popups should look similar in the app)

### ISSUE THREAD

**Issue by Adrian-Moldovan** [fnitu/edu-hospice#94]
@gabstoi @irinmo please provide **ONE** standard design for a popup considering the model in Angular Material:
https://material.angular.io/components/dialog/examples#dialog-content

### Recommendations:
- @RaduMS the popup should ALWAYS have a closing **button** on the top right side (please make sure it is a button, not a text)
- the popup should have a main title
- the popup should display the action buttons at the bottom - right side, in the same order (Cancel, OK), (Dismissing action, confirming action) - Dismissive actions (1) are placed to the left of confirming actions.
- the **course registration button** should have the same design on each popup (and not only); 
- @RaduMS please investigate the option to create a component or at least have a "registration-button" class in the whole application.
- Also consider that the design of the button is already provided by the UI/UX team:
![image](https://user-images.githubusercontent.com/5821972/144097683-ca1119f9-67af-44fd-a1d3-d546e321fe78.png)

### Popups that should be redesigned (incomplete list)
- upload profile picture
- course details before authentication
- course details after authentication
- admin: course edit section
- admin: course edit content
- admin: course content resources
- the confirmation dialog component(used in course section delete, user registration confirmation, etc...)

**Comment by gabstoi** [comment]
Screen of redesigned Admin: course --> Delete section

![image](https://user-images.githubusercontent.com/93341303/146957485-2a475903-66a7-42f5-838e-3651d9c376a9.png)

**Comment by gabstoi** [comment]
Screen of redesigned Admin:course --> Edit content 

![image](https://user-images.githubusercontent.com/93341303/146957818-a5bbb0b4-bcd5-4212-ba77-c5926a616905.png)

**Comment by Adrian-Moldovan** [comment]
@RaduMS please use css variables to implement the 
- background colors of the buttons, 
- the font size, 
- the line height, 
- the font-family

**Comment by irinmo** [comment]
Interaction - first one from this list: https://material.angular.io/components/dialog/examples#dialog-content

**Comment by Adrian-Moldovan** [comment]
Please implement the following UI/UX elements 
- the login button from the sign in interface should be similar to the register course button (blue background)
- the register button from the recommended courses cards should have a smaller font, similar to the registration popup button

**Comment by RaduMS** [comment]
Hi all, 

The button from recover-password-enter-email should be blue or green?

![2022-02-13_16h05_39](https://user-images.githubusercontent.com/38107415/153756915-4a085eac-86f7-4a2c-9372-bbdf52defc69.png)

**Comment by Adrian-Moldovan** [comment]
Yes, use the blue button

**Comment by Adrian-Moldovan** [comment]
Implemented
