### ISSUE TITLE
Redesign the user profile section

### ISSUE THREAD

**Issue by Adrian-Moldovan** [fnitu/edu-hospice#95]
@gabstoi @irinmo please provide "an impactful design" for the user profile section. 

After redesigning the course cards, the user profile section is no longer on the same design idea with the application design. Perhaps we should use something less colorful.

**Comment by irinmo** [comment]
![Screenshot 2022-02-03 at 19 16 51](https://user-images.githubusercontent.com/42898241/152394234-b44666db-14f3-4d30-ab63-d43004aaeabb.png)

**Comment by irinmo** [comment]
![Screenshot 2022-02-03 at 19 18 36](https://user-images.githubusercontent.com/42898241/152394660-37ca2a85-f8ae-433e-bc3f-66159aa8d2bd.png)

**Comment by Adrian-Moldovan** [comment]
Implemented
