### ISSUE TITLE
Provide CSS variables for the app color scheme 

### ISSUE THREAD

**Issue by Adrian-Moldovan** [fnitu/edu-hospice#98]
In order to standardize the color scheme, especially for the courses status, a set of CSS variables should be specified

The **UI / UX team** will provide a print screen of the  courses popup and the hex values used in the design.

The **front-end** should specify in a response for this issue the name of the variables that have been created.

The related issues should point to this issue in order to clearly define the colors used in the implementation.

**Comment by irinmo** [comment]
![Screenshot 2021-12-07 at 20 23 19](https://user-images.githubusercontent.com/42898241/145085287-5ca50b9a-14dc-425e-a4e4-ca5b8e1b55dc.png)
![Screenshot 2021-12-07 at 20 23 11](https://user-images.githubusercontent.com/42898241/145085294-61e875ba-c45a-4fc7-8365-7fae2ba9175c.png)
![Screenshot 2021-12-07 at 20 23 03](https://user-images.githubusercontent.com/42898241/145085297-9081ab0a-54e3-412c-ba10-5c2a91b307a0.png)
![Screenshot 2021-12-07 at 20 22 44](https://user-images.githubusercontent.com/42898241/145085299-7d119635-71b2-4b05-9f81-f9d4b43c56f9.png)

**Comment by irinmo** [comment]
EE9F8C / A7A377 / D4ECF6 / F4E1C2

**Comment by razvantudorache** [comment]
$themeColorError: #EE9F8C;
$themeColorSuccess: #A7A377;
$themeColorInfo: #D4ECF6;
$themeColorWarning: #F4E1C2;

**Comment by Adrian-Moldovan** [comment]
Implemented, to be referenced in future implementations
